### ISSUE TITLE
开启oidc后, 每次进入主页都会不停的弹窗

### ISSUE THREAD

**Issue by 4meepo** [wingfeng/zentao-oidc#2]
版本, 开源版 12.5.3. 每次进入首页,都会弹窗. 弹窗内容为 `10.0版本以后各个视图主页提供了全新的视图，您要启用新的视图布局吗？`.

点取消就不会弹了, 点确定会一直弹. 啥情况啊. 

https://user-images.githubusercontent.com/28745416/203549384-289a2822-beb6-4a04-b740-78263e268de0.mov

**Comment by 4meepo** [comment]
通过改了几行源码修复了

**Comment by bolidewang** [comment]
> 通过改了几行源码修复了

请教一下，你是如何在验证通过后绑定上禅道用户的？https://github.com/wingfeng/zentao-oidc/issues/3#issue-1518662827
